# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dbec-oregon.org
title: Diversified Builders & Engineers Council
email: info@dbec-oregon.org
author: David Molina
description: "Diversified Builders & Engineers Council (DBEc), a nonprofit
and Oregon/SW Washington Hispanic Contractors Association."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com
  - title: github
    url: https://github.com
  - title: linkedin
    url: https://linkedin.com
